### ISSUE TITLE
Option to work with lowest, second lowest, etc position instead of 0.1, 1 and 10.

### ISSUE THREAD

**Issue by KillyMXI** [nmsmith22389/vscode-incrementor#9]
I find 0.1 to be quite limiting. Usually, numbers are written with the precision that makes sense for them and can be taken into account.

`1 -> 2` (lowest)
`0.001 -> 0.002` (lowest)
`0.16 -> 0.17` (lowest)
`0.16 -> 0.26` (second lowest)
`0.16 -> 1.16` (third lowest)
`1 -> 101` (third lowest)

Number of positions after decimal point should be kept, obviously.
`0.19 -> 0.20 -> 0.21` (lowest)

**Comment by nmsmith22389** [comment]
This is a very good idea! I haven't had much time lately to work on this but it is definitely something I can look into adding. Thanks!
